# Generated by Django 3.2.6 on 2021-08-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phoneno', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
