# Generated by Django 3.2.6 on 2021-08-30 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CommercialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('sell', 'SELL'), ('rent', 'RENT')], max_length=255)),
                ('property_type', models.CharField(choices=[('booth', 'Booth'), ('showroom', 'Showroom'), ('cp', 'Commercial Plot')], max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=500)),
                ('sub_locality', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_no', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.IntegerField()),
                ('ar_units', models.CharField(choices=[('feet', 'sq.ft'), ('yards', 'yards')], default='yards', max_length=25)),
                ('dim_length', models.IntegerField(blank=True, null=True)),
                ('dim_breadth', models.IntegerField(blank=True, null=True)),
                ('floors', models.IntegerField()),
                ('possession', models.CharField(choices=[('ready to move', 'Ready To Move'), ('within 2 months', 'Within 2 Months'), ('within 3 months', 'Within 3 Months')], default='none', max_length=255)),
                ('furnishing', models.CharField(choices=[('furnished', 'FURNISHED'), ('semi', 'SEMI-FURNISHED'), ('un', 'UNFURNISHED')], max_length=255)),
                ('availability', models.CharField(choices=[('uc', 'UNDER CONSTRUCTION'), ('rm', 'READY TO MOVE')], default='uc', max_length=255)),
                ('parkingspace', models.BooleanField(blank=True, null=True)),
                ('ageofproperty', models.IntegerField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('expected_price', models.IntegerField()),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_commercial', models.BooleanField(default=True)),
                ('amenities', models.ManyToManyField(blank=True, to='commercial.CommercialAmenity')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
