# Generated by Django 3.2.6 on 2021-08-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
                ('dimension', models.CharField(max_length=299)),
                ('floors', models.CharField(max_length=340)),
            ],
        ),
    ]
