# Generated by Django 3.2.6 on 2021-08-21 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_rooms', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='propertyPossesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession_type', models.CharField(default='Ready to move', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sell', 'SELL'), ('rent', 'RENT'), ('pg', 'PG')], max_length=255)),
                ('property_type', models.CharField(choices=[('ap', 'APARTMENT'), ('kothi', 'KOTHI'), ('ih', 'INDEPENDENT HOUSE/VILLA'), ('plot', 'PLOT'), ('sa', 'STUDIO APARTMENT'), ('other', 'OTHER')], max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=500)),
                ('sub_locality', models.CharField(blank=True, max_length=255, null=True)),
                ('house_no', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.IntegerField()),
                ('dim_length', models.IntegerField(blank=True, null=True)),
                ('dim_breadth', models.IntegerField(blank=True, null=True)),
                ('floors', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('balconies', models.IntegerField(blank=True, null=True)),
                ('furnishing', models.CharField(choices=[('furnished', 'FURNISHED'), ('semi', 'SEMI-FURNISHED'), ('un', 'UNFURNISHED')], max_length=255)),
                ('availability', models.CharField(choices=[('uc', 'UNDER CONSTRUCTION'), ('rm', 'READY TO MOVE')], default='uc', max_length=255)),
                ('parkingspace', models.BooleanField(blank=True, null=True)),
                ('ageofproperty', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('expected_price', models.IntegerField()),
                ('price_per_marla', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('otherrooms', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residential.otherrooms')),
                ('possession', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='residential.propertypossesion')),
            ],
        ),
    ]
