# Generated by Django 3.2.6 on 2021-08-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialdetails',
            name='ar_units',
            field=models.CharField(choices=[('feet', 'sq.ft'), ('yards', 'yards')], default='yards', max_length=25),
        ),
        migrations.AlterField(
            model_name='propertypossesion',
            name='possession_type',
            field=models.CharField(max_length=500),
        ),
    ]
