# Generated by Django 3.2.6 on 2021-08-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0002_auto_20210821_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentialdetails',
            name='otherrooms',
        ),
        migrations.AddField(
            model_name='residentialdetails',
            name='otherrooms',
            field=models.ManyToManyField(blank=True, null=True, to='residential.OtherRooms'),
        ),
    ]
