# Generated by Django 3.2.6 on 2021-08-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0004_propertyimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
