# Generated by Django 3.2.6 on 2021-08-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0009_alter_residentialdetails_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialdetails',
            name='otherrooms',
            field=models.ManyToManyField(blank=True, to='residential.OtherRooms'),
        ),
    ]
