# Generated by Django 3.2.6 on 2021-08-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0011_residentialdetails_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
